### ISSUE TITLE
Error when build docker

### ISSUE THREAD

**Issue by tuan97anton** [vedran97/ros1-template-workspace#1]
ERROR: failed to solve: process "/bin/sh -c export DEBIAN_FRONTEND=noninteractive &&    /scripts/create-user.bash $USERNAME $USER_UID $USER_GID &&    /scripts/setup-ros-dev-environment.bash $USERNAME $WORKSPACE_PATH &&    rm -rf /install-resources &&    rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 127

**Comment by vedran97** [comment]
I will take a look into it soon! Thanks for reporting it man! Give me some time please!

**Comment by vedran97** [comment]
@tuan97anton  Can you mention what are your system specs and , if possible , once the script fails, can you attach the entire log file? I just cloned this repo and built it according to the instructions mentioned in the Readme.md , and it built successfully. My Host OS is 5.15.0-58-generic #64~20.04.1-Ubuntu SMP on a Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
